# 正式环境
spring:
  devtools:
    restart:
      # 热重启
      enabled: false
  datasource:
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/icu