server:
  port: 8081

spring:
  application:
    name: icu-backstage
  profiles:
    active: test
  redis:
    database: 1
    host: 127.0.0.1
    timeout: 10s
    lettuce:
      pool:
        max-active: 200
        max-wait: -1ms

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: del

sa-token:
  jwt-secret-key: icu-backstage-token
  token-name: icu-backstage-token

logging:
  level:
    com.baomidou.mybatisplus.samples: debug