server:
  port: 8081

spring:
  application:
    name: icu-backstage
  profiles:
    active: test

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: del

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples: debug